version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: token-bridge-app
    ports:
      - "1001:1001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/tokenmint_global?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend-network

networks:
  backend-network:
    external: true
