version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: token-bridge-server
    ports:
      - "1001:1001"
    environment:
      # JSP Configuration
      SPRING_MVC_VIEW_PREFIX: /WEB-INF/views/
      SPRING_MVC_VIEW_SUFFIX: .jsp
      
      # Database Configuration for TokenMint Global
      SPRING_TOKENMINTGLOBAL_DATASOURCE_JDBC_URL: jdbc:mysql://tokenmint-mysql:3306/tokenmint_global?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_TOKENMINTGLOBAL_DATASOURCE_USERNAME: root
      SPRING_TOKENMINTGLOBAL_DATASOURCE_PASSWORD: root
      SPRING_TOKENMINTGLOBAL_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # Primary Database Configuration (for JPA)
      SPRING_DATASOURCE_URL: jdbc:mysql://tokenmint-mysql:3306/tokenmint_global?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      
      # Hibernate Properties
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      
      # Redis Configuration
      MOCK_REDIS: "Y"
      
      # UI and Service URLs
      TOKENMINT_UI_PAGE: http://localhost:3000/tokenmint
      VERIFY_ADDRESS_URL: http://localhost:1001/tokenmint/server/verify-address/
      LOAD_UI_URL: http://localhost:1001/tokenmint/server/load-ui/
      GAME_TOKEN_TRANSFER_EVENT_LISTENER_URL: http://game-server:8080/battlegrounds/tokenTransferEventListener
      
      # Internal Service URLs
      INTERNAL_VERIFY_ADDRESS_URL: http://web3-gateway:2001/utility/verifyAddress
      INTERNAL_TRANSFER_TOKENS_URL: http://web3-gateway:2001/web3-gateway/tokenmint/transferTokensFromGame
      
      # Server Configuration
      SERVER_PORT: "1001"
      
      # Logging Configuration
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_MONOLITH: DEBUG
      LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    networks:
      - tokenmint-ecosystem
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  tokenmint-ecosystem:
    external: true
